### ISSUE TITLE
Curious about a change

### ISSUE THREAD

**Issue by strider72** [romuloalves/free-asp-upload#1]
I had a slightly older version of the code, and I've figured out that the only notable change in the newest version is that you've removed a "file exists" check from Public Sub Save(path) right around line 76:

     if fs.FileExists(path & newFileName) then ' use the file system object to check the current file's existence
         session("write_error")="One or more file name already exists."
         response.write("<span class='redFont'>" & newFileName & " exists and could not be saved; please rename and try again.</span><br>") ' the file exists so throw an error
      else

Is there any particular reason you removed this?  Does the newer version simply overwrite existing files now?

(Note, the Changelog at the top of my older version matches the "Original Changelog" you show in the readme, so this removal was not logged)

**Comment by romuloalves** [comment]
Hi @strider72 .
Sorry, I never saw this issue until now, I don't know if I didn't receive the notification or what happened.

I created this repo with the version that I had of the code to use in the future if I need.
I really don't know if it's the last version of the lib nor if it's changed of not.

I don't know if an ex-colleage modified it. 😞
